[package]
name = "rust"
version = "0.1.0"
authors = ["George Typaldos <george.typaldos@yale.edu>"]
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
lazy_static = "1.5.0"
libc = "0.2.169"
